Job Portal App
AhsanBytes/job_portal_app pull request #1
Opened 2024-09-20 10:08 UTC by AhsanBytes

2024-09-20 12:14 UTC, suleman-uzair requested changes

2024-09-20 12:14 UTC, suleman-uzair commented on Gemfile
> +gem 'faker'
Add `development` and/or `test` gems in their groups instead of defining the group in front of each gem and the rest above the groups.

2024-09-20 12:14 UTC, suleman-uzair commented on app/assets/stylesheets/application.tailwind.css
> +*/
Unused/commented code should be removed.

2024-09-20 12:14 UTC, suleman-uzair commented on app/controllers/jobs_controller.rb
> +    @departments = Department.limit(7)
Use already defined `before_action :set_departments` .

2024-09-20 12:14 UTC, suleman-uzair commented on app/controllers/jobs_controller.rb
> +      flash[:notice] = 'Job was not deleted.'
Again, error messages should be clear.

2024-09-20 12:14 UTC, suleman-uzair commented on app/controllers/jobs_controller.rb
> +    @job = Job.find(params[:id])
```suggestion
    @job = Job.find_by(id: params[:id])
```

difference between both `find` and `find_by`?

2024-09-20 12:14 UTC, suleman-uzair commented on app/controllers/users_controller.rb
> +  before_action :authenticate_user!
Move it to ApplicationController since authentication is required for most of the methods.

2024-09-20 12:14 UTC, suleman-uzair commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
Again, `find` => `find_by`

2024-09-20 12:14 UTC, suleman-uzair commented on app/javascript/channels/index.js
> +// channels.keys().forEach(channels);
commented code.

2024-09-20 12:14 UTC, suleman-uzair commented on app/javascript/channels/job_notification_channel.js
> +// document.addEventListener("turbolinks:load", () => {
commented code.

2024-09-20 12:14 UTC, suleman-uzair commented on app/javascript/channels/job_notification_channel.js
> +        debugger
Debuggers are not allowed!

2024-09-20 12:14 UTC, suleman-uzair commented on app/models/department.rb
> +  validates :dep_name, uniqueness: true
```suggestion
  validates :dep_name, presence: true, uniqueness: true
```

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "block shadow rounded-md p-2 mt-1 w-1/2" %>
`autofocus: true` should be in `f.text_field :name`.

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/jobs/_form.html.erb
> +    <%= form.check_box :active, class: "mr-2" %> <%= form.label :active, 'Active', class: "inline" %>
```suggestion
    <%= form.check_box :active, class: "mr-2" %>
    <%= form.label :active, 'Active', class: "inline" %>
```

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/jobs/_job.html.erb
> +        <% job.skills.each do |skill| %>
Define `@job_skills_names` in the controller.

```suggestion
        <% @job_skills_names.each do |skill| %>
```

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/jobs/index.html.erb
> +      <div class="w-full flex justify-between items-center pb-8">
Indentation.

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/jobs/index.html.erb
> +        </form>
Use rails form and fields instead of plain HTML.

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/jobs/index.html.erb
> +          <%= render job, @applied_for_job %>
Is this `@applied_for_job` variable defined?

```suggestion
          <%= render job %>
```

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/jobs/_form.html.erb
> +    <%= form.collection_select :department_id, @departments, :id, :dep_name, prompt: "Select a Department", required: true, class: "block shadow rounded-md p-2 mt-1 w-full" %>
When `render 'form'` is called from the new and edit file, @departments and @skills are passed as local variables.

```suggestion
    <%= form.collection_select :department_id, departments, :id, :dep_name, prompt: "Select a Department", required: true, class: "block shadow rounded-md p-2 mt-1 w-full" %>
```

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/jobs/_form.html.erb
> +    <%= form.collection_check_boxes :skill_ids, @skills, :id, :skill_name, required: true, class: "space-y-2" %>
```suggestion
    <%= form.collection_check_boxes :skill_ids, skills, :id, :skill_name, required: true, class: "space-y-2" %>
```

2024-09-20 12:14 UTC, suleman-uzair commented on app/views/jobs/_job.html.erb
> +              <% job.users.each do |user| %>
Should define a variable named `job_users` and add the table if that contains any value.

2024-09-20 12:14 UTC, suleman-uzair commented on app/controllers/users_controller.rb
> +    @most_recent_job = @user.user_jobs.order(created_at: :desc).first
```suggestion
    @most_recent_user_job
```

2024-09-20 12:14 UTC, suleman-uzair commented on config/environments/test.rb
> +
Remove it.

2024-09-20 12:14 UTC, suleman-uzair commented on test/controllers/jobs_controller_test.rb
> +    assert_equal jobs.count, 2
Invalid test case.

2024-09-20 12:14 UTC, suleman-uzair commented on test/controllers/jobs_controller_test.rb
> +  test "candidate can apply for job" do
Add another test case explaining user can't apply for same job multiple times.

2024-09-20 12:14 UTC, suleman-uzair commented on test/controllers/users_controller_test.rb
> +    assert @user.user_jobs.order(created_at: :desc).first.valid?
Did not hit any controller method.

2024-09-20 12:14 UTC, suleman-uzair commented on test/mailers/job_mailer_test.rb
> +  end
Deliver the mail and check the delivery status/count.

2024-09-20 12:14 UTC, suleman-uzair commented on test/models/user_jobs_test.rb
> +    assert_not again_apply.valid?
Check for error message in this case.

2024-09-20 12:14 UTC, suleman-uzair commented on test/views/job_partial_test.rb
> +    creator_id: 1
```suggestion
    job = Job.create!(
       title: "Hello, world",
       description: "this is testing the rich text and jobs creating functionality",
       company: "Techie",
       work_space_type: 1,
       location: "Lahore", 
       lead_source: "linkedin",
       active: true,
       department_id: 1, 
       creator_id: 1
    )
```

2024-09-20 15:26 UTC, M-Ramzan1 requested changes

2024-09-20 15:26 UTC, techie-progammer commented on app/channels/job_notification_channel.rb
> +    debugger
.

2024-09-20 15:26 UTC, techie-progammer commented on app/controllers/application_controller.rb
> +  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
Feel free to rescue 404 here.

2024-09-20 15:26 UTC, techie-progammer commented on app/controllers/root_controller.rb
> +    end
```suggestion
     redirect_to jobs_path if current_user
```

2024-09-20 15:26 UTC, techie-progammer commented on app/helpers/job_applicants_helper.rb
> +module JobApplicantsHelper
Feel free to remove these empty helpers.

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/models/department.rb
> +  validates :dep_name, uniqueness: true
If table name is `departments` then I think, there is no need to add `dep` in `name` column. Thoughts?
```suggestion
  validates :name, presence: true
  validates :name, uniqueness: true
```

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/models/job.rb
> +  has_many :users, through: :user_jobs
Initially, I thought these are `creators` but there is a separate association name `creator`.
I think, `applicants` will be more suitable here :thinking:

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/models/skill.rb
> +  has_many :job_skills
Should it be?
```suggestion
  has_many :job_skills, dependent: :destroy
```

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/policies/job_policy.rb
> +    # debugger
.

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/policies/job_policy.rb
> +    user.admin?
```suggestion
    create?
```

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/policies/job_policy.rb
> +        scope.includes([ :department, :skills, :rich_text_description ]).where(active: true)
Move this `where(active: true)` to model.

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/views/devise/shared/_links.html.erb
> +    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600", data:
Do we need this `OmniAuth::Utils.camelize(provider)`?

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/views/jobs/_form.html.erb
> +    </div>
Feel free to move it in a partial.

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/views/jobs/_job.html.erb
> +        <% job.skills.each do |skill| %>
`each` vs `find_each`

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/views/jobs/_job.html.erb
> +        <% if job.user_jobs.exists? %>
```suggestion
        <% if job.users.exists? %>
```

2024-09-20 15:26 UTC, M-Ramzan1 commented on app/controllers/users_controller.rb
> +    @most_recent_job = @user.user_jobs.order(created_at: :desc).first
Please don't retrieve middle table entries.

2024-09-20 15:26 UTC, M-Ramzan1 commented on config/routes.rb
> +  resources :users, only: [:show]
**Admin can add HR** functionality not implemented.

2024-09-20 15:26 UTC, M-Ramzan1 commented on db/migrate/20240909114122_create_skills.rb
> +      t.string :skill_name
```suggestion
      t.string :name
```

2024-09-20 15:26 UTC, M-Ramzan1 commented on db/schema.rb
> +    t.string "lead_source"
Please add `null: false` if these fields are mandatory.

2024-09-20 15:26 UTC, M-Ramzan1 commented on db/schema.rb
> +    t.string "email", default: "", null: false
```suggestion
    t.string "email", null: false
```

2024-09-20 15:26 UTC, M-Ramzan1 commented on db/seeds.rb
> +  Department.find_or_create_by(dep_name: dep_name)
Feel free to replace `find_or_create` with `create!`.

2024-09-20 15:26 UTC, M-Ramzan1 commented on test/controllers/jobs_controller_test.rb
> +    get jobs_path
No assertion in this test case.

2024-09-23 08:11 UTC, suleman-uzair requested changes

2024-09-23 08:11 UTC, suleman-uzair commented on app/views/jobs/_form.html.erb
> +  <% end %>
Is this code tested?
Also, is it possible to use `app/views/devise/shared/_error_messages.html.erb` partial here?

2024-09-23 08:11 UTC, suleman-uzair commented on app/views/jobs/_form.html.erb
> +    <%= form.collection_select :department_id, @departments, :id, :name, prompt: "Select a Department", required: true, class: "block shadow rounded-md p-2 mt-1 w-full" %>
```suggestion
    <%= form.collection_select :department_id, departments, :id, :name, prompt: "Select a Department", required: true, class: "block shadow rounded-md p-2 mt-1 w-full" %>
```

2024-09-23 08:11 UTC, suleman-uzair commented on app/views/jobs/_form.html.erb
> +    <%= form.collection_check_boxes :skill_ids, @skills, :id, :name, required: true, class: "space-y-2" %>
```suggestion
    <%= form.collection_check_boxes :skill_ids, skills, :id, :name, required: true, class: "space-y-2" %>
```

2025-01-07 17:39 UTC, merged